name: build docs

on:
  push:
    branches:
    - main
permissions:
  contents: write
jobs:
  adoc_build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs --backend=html5 *.adoc"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
         folder: docs
